### PR TITLE
Dashboard Fixes

### LINKED ISSUE #398: Devices not connected
After I connected my health device (health kit) and then I reconnected using iPhone but setting shows "connect device"

Also when I click on open setting it took me to settings not matching with what was stated in instructions 

See screenshots image
image
image
image

### PR DESCRIPTION
**Pull request by samisuteria**
- Set last 2 months of data to show up if no current event for participant and 300 miles for a default commitment. 

Screenshot 2020-08-15 at 19 00 40

### CODE REVIEW

File: Steps4Impact/DashboardV2/DashboardDataSource.swift [hunk 1]
```diff
@@ -74,8 +74,17 @@ class DashboardDataSource: TableViewDataSource {
         self.eventTimelineString = DataFormatters
           .formatDateRange(value: (start: event.challengePhase.start, end: event.challengePhase.end))
         self.eventLengthInDays = event.lengthInDays
+        self.commitment = event.commitment?.miles ?? 300
+      } else {
+        self.eventName = "No Current Event"
+        let monthsInSeconds: Double = 60 * 60 * 24 * 30
```
Comment (compnerd) [inline Steps4Impact/DashboardV2/DashboardDataSource.swift]: Should we figure out the time in the month using NSCalendar rather than assuming 30 days?

File: Steps4Impact/DashboardV2/DashboardDataSource.swift [hunk 2]
```diff
@@ -74,8 +74,17 @@ class DashboardDataSource: TableViewDataSource {
...
+        self.eventTimeline = DateInterval(
+          start: Date(timeIntervalSinceNow: -monthsInSeconds),
+          end: Date(timeIntervalSinceNow: monthsInSeconds))
+        self.eventTimelineString = "Last 2 Months"
+        self.eventLengthInDays = self.eventTimeline.start.daysUntil(self.eventTimeline.end)
+        self.commitment = 300
```
Comment (compnerd) [inline Steps4Impact/DashboardV2/DashboardDataSource.swift]: Why 300?

File: Steps4Impact/DashboardV2/DashboardDataSource.swift (hunk 1 above)
Comment (aalimmulji) [reply Steps4Impact/DashboardV2/DashboardDataSource.swift]: @compnerd This is just a fallback case when we don't have an active event. And, in this case it's just used to create a 60 days period for a dummy event.

**Review by aalimmulji — APPROVED** [review]

**Review by faysal-ali — APPROVED** [review]
"No current event" & "Last 2 months" could be in localized.strings as these are default values
